name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Commit changes - Your Email 23f2004837@ds.study.iitm.ac.in
      run: |
        echo "Running!"
